name: ebank
description: Mobile banking application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  go_router: ^12.0.0
  flutter_riverpod: ^2.3.10
  hooks_riverpod: ^2.4.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  fl_chart: ^0.64.0
  sqflite: ^2.3.0
  equatable: ^2.0.5
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
